### ISSUE TITLE
Making Remote Branch Configurable 

### ISSUE THREAD

**Issue by codenio** [khanhicetea/gh-actions-hugo-deploy-gh-pages#2]
Hi, 

Thanks for this excellent action 👍. It would be more helpful if we could make both remote repo and remote branch configurable.
https://github.com/khanhicetea/gh-actions-hugo-deploy-gh-pages/blob/a3d05187cc116f2b9dee157b4976d52607335e31/entrypoint.sh#L22

Thoughts ?

**Comment by khanhicetea** [comment]
Thanks,

You can use the shell environment variable default values to make it configurable! Feel free to make a PR :smile:

**Comment by codenio** [comment]
@khanhicetea created a PR for the same, have a look and let me know for updates or changes.
let's get this merged.

**Comment by codenio** [comment]
@khanhicetea thanks

**Comment by khanhicetea** [comment]
Btw, you forgot `$` symbol in default env value syntax

So I fix it in this PR #4
