### ISSUE TITLE
CNAME placement

### ISSUE THREAD

**Issue by JamieCrisman** [khanhicetea/gh-actions-hugo-deploy-gh-pages#6]
This worked great. I think the only thing that's not 100% clear is you should have your CNAME in the static folder (rather than the root directory that it's typically read from). It's kind of taking advantage of hugo to solve a github requirement. So it may be helpful to note in the readme.

**Comment by khanhicetea** [comment]
Thanks for remind, I updated the README file in this commit : https://github.com/khanhicetea/gh-actions-hugo-deploy-gh-pages/commit/02dbc3aedcae06eac41dd43d82c226aad872c367
